apiVersion: tf.upbound.io/v1beta1
kind: Workspace
metadata:
  name: example-inline
  annotations:
    crossplane.io/external-name: demopsql
spec:
  forProvider:
    # Workspaces default to using a remote source - like workspace-remote.yaml.
    # For simple cases you can use an inline source to specify the content of
    # main.tf as opaque, inline HCL.
    source: Inline
    module: |
      // Outputs are written to the connection secret.
      output "psql_name" {
        value = google_sql_database_instance.main.name
      }

      resource "random_id" "example" {
        byte_length = 4
      }

      // The google provider and remote state are configured by the provider
      // config - see providerconfig.yaml.
      resource "google_sql_database_instance" "main" {
        name             = "main-instance-${random_id.example.hex}"
        database_version = "POSTGRES_14"
        region           = "europe-west3"

        settings {
          # Second-generation instance tiers are based on the machine
          # type. See argument reference below.
          tier = "db-f1-micro"
        }  
      }  
  writeConnectionSecretToRef:
    namespace: demo
    name: terraform-workspace-example-inline
